SET NAMES utf8mb4;

CREATE DATABASE IF NOT EXISTS app_user DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT All PRIVILEGES ON app_user.* TO 'yt123456' @'%';

USE app_user;

DROP TABLE IF EXISTS agent_user;
CREATE TABLE agent_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    avatar VARCHAR(255)
);